-- 010: Persona sharing + DM scenario cleanup

-- Share tokens (generated by owner)
CREATE TABLE IF NOT EXISTS share_tokens (
  token text PRIMARY KEY DEFAULT gen_random_uuid()::text,
  persona_id uuid NOT NULL REFERENCES personas(id) ON DELETE CASCADE,
  created_by uuid NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
  expires_at timestamptz NOT NULL DEFAULT now() + interval '7 days',
  used_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Persona shares (junction: who has access)
CREATE TABLE IF NOT EXISTS persona_shares (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  persona_id uuid NOT NULL REFERENCES personas(id) ON DELETE CASCADE,
  client_id uuid NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
  share_token text,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(persona_id, client_id)
);

CREATE INDEX IF NOT EXISTS idx_persona_shares_client ON persona_shares(client_id);
CREATE INDEX IF NOT EXISTS idx_persona_shares_persona ON persona_shares(persona_id);

-- Cleanup: remove "post" scenario_files for DM-only clones
DELETE FROM scenario_files
WHERE slug = 'post'
  AND persona_id IN (SELECT id FROM personas WHERE type = 'dm');

-- Cleanup: remove "post" key from personas.scenarios jsonb for DM-only clones
UPDATE personas
SET scenarios = scenarios - 'post'
WHERE type = 'dm' AND scenarios ? 'post';
